#include QMK_KEYBOARD_H

#include "sombrer_keymap.h"

enum custom_keycodes {
    LNG_SWC = SAFE_RANGE,
    FUNNY,
    SELWORD,
    ENDW,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |  Q   |  W   |  F   |  P   |  B   |                    |  J   |  L   |  U   |  Y   | ; :  | - _  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |ESC/~ | A/◆  | R/⎇  | S/⎈  | T/⇧  |  G   |                    |  M   | N/⇧  | E/⎈  | I/⎇  | O/◆  | ' "  |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |  Z   |  X   |  C   |  D   |  V   | [ {   |    | ] }   |  K   |  H   | , <  | . >  | / ?  |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |LNG_SW|󰌒/NAV | / SPC   /      \ BSPC  \  |⏎/SYM | RGUI |TG_GMG|
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_COLEMAK] = LAYOUT(
  XXXXXXX , KC_1   , KC_2    , KC_3    , KC_4    , KC_5 ,                         KC_6 , KC_7    , KC_8    , KC_9   , KC_0    , XXXXXXX,
  XXXXXXX , KC_Q   , KC_W    , KC_F    , KC_P    , KC_B ,                         KC_J , KC_L    , KC_U    , KC_Y   , KC_SCLN , KC_MINS,
  QK_GESC , HOME_A , HOME_R  , HOME_S  , HOME_T  , KC_G ,                         KC_M , HOME_N  , HOME_E  , HOME_I , HOME_O  , KC_QUOT,
  XXXXXXX , KC_Z   , KC_X    , KC_C    , KC_D    , KC_V , KC_LBRC ,     KC_RBRC , KC_K , KC_H    , KC_COMM , KC_DOT , KC_SLSH , XXXXXXX,
                     XXXXXXX , LNG_SWC , NAV_TAB ,     KC_SPC     ,        KC_BSPC     , SYM_ENT , KC_RGUI , TG_GMG
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * | CAPS |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   | GRV  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                    |  Y   |  U   |  I   |  O   |  P   | MINS |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |QK_GES|LGUIA |LALTS |LCTLD |LSFTF |  G   |                    |  H   |RSFTJ |RCTLK |RALTL |RGUICL| QUOT |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * | LSFT |  Z   |  X   |  C   |  V   |  B   | LBRC  |    | RBRC  |  N   |  M   | COMM | DOT  | SLSH | RSFT |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |LNG_SW|NAV_TA| / SPC   /      \ BSPC  \  |SYM_EN| RGUI |  TG  |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_QWERTY] = LAYOUT(
  KC_CAPS , KC_1  , KC_2    , KC_3    , KC_4    , KC_5 ,                         KC_6 , KC_7    , KC_8    , KC_9    , KC_0    , KC_GRV ,
  KC_TAB  , KC_Q  , KC_W    , KC_E    , KC_R    , KC_T ,                         KC_Y , KC_U    , KC_I    , KC_O    , KC_P    , KC_MINS,
  QK_GESC , LGUIA , LALTS   , LCTLD   , LSFTF   , KC_G ,                         KC_H , RSFTJ   , RCTLK   , RALTL   , RGUICLN , KC_QUOT,
  KC_LSFT , KC_Z  , KC_X    , KC_C    , KC_V    , KC_B , KC_LBRC ,     KC_RBRC , KC_N , KC_M    , KC_COMM , KC_DOT  , KC_SLSH , KC_RSFT,
                    XXXXXXX , LNG_SWC , NAV_TAB ,     KC_SPC     ,        KC_BSPC     , SYM_ENT , KC_RGUI , XXXXXXX
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                    |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |  $   |  +   |  (   |  )   |  @   |                    |  |   | [ {  | ] }  |  =   |  *   |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |  !   |  #   |  {   |  }   |  ~   |  \    |    | / ?   |  &   | - _  |  _   |  %   |  ^   |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |      | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_SYM] = LAYOUT(
  KC_F1   , KC_F2   , KC_F3   , KC_F4   , KC_F5   , KC_F6   ,                         KC_F7   , KC_F8    , KC_F9    , KC_F10  , KC_F11  , KC_F12 ,
  XXXXXXX , KC_1    , KC_2    , KC_3    , KC_4    , KC_5    ,                         KC_6    , KC_7    , KC_8    , KC_9    , KC_0    , XXXXXXX,
  XXXXXXX , KC_DLR  , KC_PLUS , KC_LPRN , KC_RPRN , KC_AT   ,                         KC_PIPE , KC_LBRC , KC_RBRC , KC_EQL  , KC_ASTR , XXXXXXX,
  XXXXXXX , KC_EXLM , KC_HASH , KC_LCBR , KC_RCBR , KC_TILD , KC_BSLS ,     KC_SLSH , KC_AMPR , KC_MINS , KC_UNDS , KC_PERC , KC_CIRC , XXXXXXX,
                      _______ , _______ , _______ ,      _______      ,          _______      , _______ , _______ , _______
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |C(KC_R| VOLU |C(KC_V|C(KC_L|                    | DOWN |RIGHT |      |C(KC_C|      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | END  | MPRV | VOLD | MNXT |      |                    | MUTE |      |      | HOME |      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |      |      | MPLY |      |      |       |    |       |  UP  | LEFT |      |      |      |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |      | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_NAV] = LAYOUT(
  _______ , _______ , _______    , _______ , _______ , _______    ,                         _______ , _______  , _______ , _______ , _______ , _______,
  _______ , _______ , C(KC_RGHT) , KC_VOLU , C(KC_V) , C(KC_LEFT) ,                         KC_DOWN , KC_RIGHT , _______ , C(KC_C) , _______ , _______,
  _______ , KC_END  , KC_MPRV    , KC_VOLD , KC_MNXT , _______    ,                         KC_MUTE , _______  , _______ , KC_HOME , _______ , _______,
  _______ , _______ , _______    , KC_MPLY , _______ , _______    , _______ ,     _______ , KC_UP   , KC_LEFT  , _______ , _______ , _______ , _______,
                      _______    , _______ , _______ ,       _______        ,          _______      , _______  , _______ , _______
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |  ⯬   |MOUSE↑|  ⯮   |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |LGUI◆ |LALT⎇ |LSFT⇧ |LCTL⎈ |      |                    |      |MOUSE←|MOUSE↓|MOUSE→|      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |      | BTN3 | BTN1 | BTN2 |      |       |    |       |      | BTN3 |WHEEL↓|WHEEL↑|      |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |      | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_MOUSE] = LAYOUT(
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,                         XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,                         XXXXXXX , KC_WBAK , KC_MS_U , KC_WFWD , XXXXXXX , XXXXXXX,
  XXXXXXX , KC_LGUI , KC_LALT , KC_LSFT , KC_LCTL , XXXXXXX ,                         XXXXXXX , KC_MS_L , KC_MS_D , KC_MS_R , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_BTN3 , KC_BTN1 , KC_BTN2 , XXXXXXX , XXXXXXX ,     XXXXXXX , XXXXXXX , KC_BTN3 , KC_WH_D , KC_WH_U , XXXXXXX , XXXXXXX,
                      _______ , _______ , _______ ,      _______      ,          _______      , _______ , _______ , _______
),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      | ESC  |  1   |  2   |  3   |  4   |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | TAB  |  Q   |  W   |  E   |  R   |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |LSFT⇧ |  A   |  S   |  D   |  F   |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |LCTL⎈ |  Z   |  X   |  C   |  V   |       |    |       |      |      |      |      |      |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |  B   |  N   | ENT  | / SPC   /      \       \  |      |      |  TG  |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
[_GAMING] = LAYOUT(
  XXXXXXX , KC_ESC  , KC_1 , KC_2 , KC_3   , KC_4 ,                         XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , KC_TAB  , KC_Q , KC_W , KC_E   , KC_R ,                         XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , KC_LSFT , KC_A , KC_S , KC_D   , KC_F ,                         XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , KC_LCTL , KC_Z , KC_X , KC_C   , KC_V , XXXXXXX ,     XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
                      KC_B , KC_N , KC_ENT ,     KC_SPC     ,          XXXXXXX      , XXXXXXX , XXXXXXX , TG_GMG
)
};

layer_state_t layer_state_set_user(layer_state_t state) {
  return update_tri_layer_state(state, _SYM, _NAV, _MOUSE);
}

//SSD1306 OLED update loop, make sure to enable OLED_ENABLE=yes in rules.mk
#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
  if (!is_keyboard_master())
    return OLED_ROTATION_180;  // flips the display 180 degrees if offhand
  return rotation;
}

// When you add source files to SRC in rules.mk, you can use functions.
const char *read_logo_l(void);
const char *read_logo_r(void);

bool oled_task_user(void) {
  if (is_keyboard_master()) {
    oled_write(read_logo_l(), false);
  } else {
    oled_write(read_logo_r(), false);
  }
    return false;
}
#endif // OLED_ENABLE

// remap shift+backspace to delete
const key_override_t delete_key_override = ko_make_basic(MOD_MASK_SHIFT, KC_BSPC, KC_DEL);

// This globally defines all key overrides to be used
const key_override_t **key_overrides = (const key_override_t *[]){
    &delete_key_override,
    NULL // Null terminate the array of overrides!
};

void change_layout(void) {
    if (colemak_layot_on) {
        layer_off(_COLEMAK);
        layer_on(_QWERTY);
        colemak_layot_on = false;
    } else {
        layer_off(_QWERTY);
        layer_on(_COLEMAK);
        colemak_layot_on = true;
    }
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode){
    case LNG_SWC:
      if (record->event.pressed) {
        register_code(KC_LGUI);
        tap_code(KC_SPC);
      } else {
        unregister_code(KC_LGUI);
        change_layout();
      }
      return false;
  }
  return true;
}
