import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]

[shell]
  program = "tmux"
  args = ["new", "-A", "-s", "default"]

[window]
  startup_mode = "Maximized"
  padding = { x=5, y=5 }

[font]
  normal = { family = "Hack Nerd Font Mono", style = "Regular" }
  bold = { family = "Hack Nerd Font Mono", style = "Bold" }
  italic = { family = "Hack Nerd Font Mono", style = "Regular Italic" }
  bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
  size = 12

[keyboard]
  bindings = [
   {key = ";", mods = "Control", action = "IncreaseFontSize"},
   {key = "-", mods = "Control", action = "DecreaseFontSize"}
  ]

# Nightfox Alacritty Colors
## name: carbonfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/carbonfox/alacritty.toml

