return {
  enabled=false,
  'miversen33/sunglasses.nvim',
  event = 'UIEnter',
  config = function()
    require('sunglasses').setup {
      filter_percent = 0.3,
      excluded_filetypes = {
        'dashboard',
        'lspsagafinder',
        'packer',
        'checkhealth',
        'mason',
        'NvimTree',
        'neo-tree',
        'plugin',
        'lazy',
        'TelescopePrompt',
        'alpha',
        'toggleterm',
        'sagafinder',
        'better_term',
        'fugitiveblame',
        'starter',
        'NeogitPopup',
        'NeogitStatus',
        'DiffviewFiles',
        'DiffviewFileHistory',
        'DressingInput',
        'spectre_panel',
        'zsh',
        'registers',
        'startuptime',
        'OverseerList',
        'Navbuddy',
        'noice',
        'notify',
        'saga_codeaction',
        'sagarename',
        'minifiles',
      },
    }
  end,
}
